#!/usr/bin/env bash

set -e -u
set -x
export LANG=C


arch=$(uname -m)
quiet=false
work_dir="work"
script_path=$(readlink -f ${0%/*})
script_dir=$(dirname ${script_path})
codename="bionic"
mirror="http://archive.ubuntu.com/ubuntu/"


# Show an INFO message
# _msg_info <message>
function _msg_info () {
    local _msg="${@}"
    echo "[LUBS Core] INFO: ${_msg}"
}

# Show an ERROR message then exit with status
# _msg_error <message> <exit code>
function _msg_error() {
    local _msg="${1}"
    local _error=${2}
    echo
    echo "[LUBS Core] ERROR: ${_msg}" >&2
    echo
    if [[ ! ${_error} = 0 ]]; then
        exit ${_error}
    fi
}

function install_ubuntu() {
    _msg_info "Installing Ubuntu to '${work_dir}/airootfs/'..."
    mkdir -p ${work_dir}/airootfs
    if ${quiet}; then
        # true
        debootstrap --arch=${arch} --merged-usr ${codename} ${work_dir}/airootfs ${mirror}  &> /dev/null
    else
        # false
        debootstrap --arch=${arch} --verbose --merged-usr ${codename} ${work_dir}/airootfs ${mirror}
    fi
    _msg_info "Ubuntu installed successfully!"
}

install_ubuntu