#!/usr/bin/env bash

set -e -u

export LANG=C


arch=$(uname -m)
quiet=false
work_dir="work"
script_path=$(readlink -f ${0%/*})
script_dir=$(dirname ${script_path})
codename="bionic"


# Show an INFO message
# _msg_info <message>
function _msg_info () {
    local _msg="${@}"
    echo "[LUBS Core] INFO: ${_msg}"
}

# Show an ERROR message then exit with status
# _msg_error <message> <exit code>
function _msg_error() {
    local _msg="${1}"
    local _error=${2}
    echo
    echo "[LUBS Core] ERROR: ${_msg}" >&2
    echo
    if [[ ! ${_error} = 0 ]]; then
        exit ${_error}
    fi
}

# Install desired packages to airootfs
function _apt_get () {
    _msg_info "Installing packages to '${work_dir}/airootfs/'..."

    if ${quiet}; then
        # true
        debootstrap --arch=${arch} --include=${@} --merged-usr ${work_dir}/airootfs/ ${codename} http://ubuntutym.u-toyama.ac.jp/ubuntu/
    else
        # false
        debootstrap --arch=${arch} --include=${@} --merged-usr ${work_dir}/airootfs/ ${codename} http://ubuntutym.u-toyama.ac.jp/ubuntu/&> /dev/null
    fi

    _msg_info "Packages installed successfully!"
}

function _chroot_init() {
    mkdir -p ${work_dir}/airootfs
    _apt_get 'linux-image-generic,grub'
}