#!/usr/bin/env bash

set -e -u

export LANG=C


arch=amd64
work_dir="work"
script_path=$(readlink -f ${0%/*})
script_dir=$(dirname ${script_path})
codename="bionic"
mirror="http://ftp.jaist.ac.jp/pub/Linux/ubuntu/"


# Show an INFO message
# _msg_info <message>
function _msg_info () {
    local _msg="${@}"
    echo "[LUBS Core] INFO: ${_msg}"
}

# Show an ERROR message then exit with status
# _msg_error <message> <exit code>
function _msg_error() {
    local _msg="${1}"
    local _error=${2}
    echo
    echo "[LUBS Core] ERROR: ${_msg}" >&2
    echo
    if [[ ! ${_error} = 0 ]]; then
        exit ${_error}
    fi
}

function install_ubuntu() {
    _msg_info "Installing Ubuntu to '${work_dir}/airootfs/'..."
    mkdir -p ${work_dir}/airootfs
    debootstrap --arch=${arch} --verbose --merged-usr ${codename} ${work_dir}/airootfs ${mirror}
    _msg_info "${codename} installed successfully!"
}

install_ubuntu